import React from "react";
import { Metadata } from "next";
import { ReactLenis } from "lenis/react";
import { Spline_Sans } from "next/font/google";
import "../globals.css";

const spline = Spline_Sans({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Web Development & AI automation",
    description: "Generated by create next app",
    verification: {
        google: "UHg0wtsc2rW9CqzIsVhdiiI-ZsqpDocFtYKRhVMX1xA",
    },
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'da' }];
}

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ lang: 'en' | 'da' }>;
}) {
    const { lang } = await params;

    return (
        <html lang={lang}>
            <body className={`${spline.className} antialiased`}>
                <ReactLenis root />
                {children}
            </body>
        </html>
    );
}
