import React from "react";
import { Metadata } from "next";
import { ReactLenis } from "lenis/react";
import { Playfair_Display, Spline_Sans } from "next/font/google";
import "./globals.css";

const spline = Spline_Sans({
    subsets: ["latin"],
});

const playfair = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Web Development & AI automation",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${spline.className} antialiased`}>
                <ReactLenis root />
                {children}
            </body>
        </html>
    );
}
